name: Build Installers

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'preview'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.SUBMODULE_REPO_DEPLOY_KEY }}
          ssh-key: ${{ secrets.SUBMODULE_REPO_DEPLOY_SSH_KEY }}
#      - name: Clone Submodule
#        run: |
#          mkdir -p $HOME/.ssh
#          echo '${{ secrets.SUBMODULE_REPO_DEPLOY_KEY }}' > $HOME/.ssh/ssh.key
#          chmod 600 $HOME/.ssh/ssh.key
#          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
#          git submodule update --init
#          git submodule foreach --recursive git reset --hard
#          git submodule set-url ./traccar-web git@github.com:cortip/traccar-web.git
#          git submodule update --init --recursive
#          git submodule set-url ./traccar-web https://github.com/cortip/traccar-web.git
#          unset GIT_SSH_COMMAND
#      - run: |
#          git submodule update --init
#          git submodule foreach --recursive git reset --hard
#      - run: git checkout ${{ github.ref_name }}
#        working-directory: ./traccar-web
#      - name: Clone Submodule
#        run: |
#          mkdir -p $HOME/.ssh
#          echo '${{ secrets.SUBMODULE_REPO_DEPLOY_KEY }}' > $HOME/.ssh/ssh.key
#          chmod 600 $HOME/.ssh/ssh.key
#          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
#          git clone git@github.com:cortip/traccar-web.git
#          unset GIT_SSH_COMMAND
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: ./gradlew build
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
          cache-dependency-path: |
            traccar-web/package-lock.json
            traccar-web/modern/package-lock.json
      - run: |
          wget -q http://cdn.sencha.com/cmd/7.1.0.15/no-jre/SenchaCmd-7.1.0.15-linux-i386.sh.zip
          unzip SenchaCmd-*.zip
          ./SenchaCmd-*.sh -q
          echo "$HOME/bin/Sencha/Cmd/" >> $GITHUB_PATH
      - run: ./traccar-web/tools/package.sh
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install innoextract makeself wine32 s3cmd
      - name: Build installers
        working-directory: ./setup
        run: |
          wget -q http://files.jrsoftware.org/is/5/isetup-5.5.6.exe
          wget -q https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4+8/OpenJDK17U-jdk_x64_windows_hotspot_17.0.4_8.zip
          wget -q https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4+8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.4_8.tar.gz
          wget -q https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4+8/OpenJDK17U-jdk_arm_linux_hotspot_17.0.4_8.tar.gz
          ./package.sh ${{ github.event.inputs.version }}
      - name: Upload installers
        working-directory: ./setup
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: s3cmd --acl-public put traccar-*.zip s3://cortip-traccar/builds/ --access_key="$S3_ACCESS_KEY" --secret_key="$S3_SECRET_KEY"
        # --host-bucket=cortip-traccar